fimad/scalpel

.travis.yml, README.md, examples/example-from-documentation/Main.hs, examples/list-all-images/Main.hs, examples/scalpel-examples.cabal, src/Text/HTML/Scalpel.hs
The examples in the documentation to deriving the Show type class,
without this GHCi will silently fail. Also add an examples directory
with full compilable examples.
=> (#6) Update and add examples

CHANGELOG.md, benchmarks/Main.hs, src/Text/HTML/Scalpel.hs, src/Text/HTML/Scalpel/Internal/Scrape.hs, src/Text/HTML/Scalpel/Internal/Scrape/StringLike.hs, src/Text/HTML/Scalpel/Internal/Scrape/URL.hs, src/Text/HTML/Scalpel/Internal/Select.hs, src/Text/HTML/Scalpel/Internal/Select/Types.hs, tests/TestMain.hs
Only compute closing tag offsets once per scraper evaluation instead of once per select evaluation.
=> More optimizations

CHANGELOG.md, README.md, scalpel.cabal, src/Text/HTML/Scalpel.hs, src/Text/HTML/Scalpel/Internal/Scrape/URL.hs
Adds a new more extensible method for scraping URLs. This function
takes a record type that can be extended in the future to further
modify the behavior of scraping URLs.
Besides the list of curl options, a new decoder option is added. The
decoder is a function that takes a curl response and turns it into a
string-like type. The default decoder attempts to infer the correct
encoding from the Content-Type header. If no character set is given
then it assumes ISO-8859-1.
There are also decoders that force UTF-8 or ISO-8859-1 for use with
websites that do a poor job of declaring their character sets.
=> (closes #11) Add scrapeUrlWithConfig

src/Text/HTML/Scalpel/Internal/Scrape.hs, src/Text/HTML/Scalpel/Internal/Select/Types.hs, tests/TestMain.hs
Tags are now passed through TagSoup's canonicalize which converts all
tag and attribute names to lower case. Similarly all tag names and
attribute names used in scrapers are lower cased prior to being
evaluated.
=> (#19) Make tag matching case insensitive

CHANGELOG.md, src/Text/HTML/Scalpel.hs, src/Text/HTML/Scalpel/Internal/Select/Combinators.hs, tests/TestMain.hs
The `match` function is exposed which can be used to create
AttributePredicate values from functions that take a string valued
attribute key and attribute value and return a boolean.
=> (#22) Allows construction of arbitrary predicates

src/Text/HTML/Scalpel/Internal/Select.hs
scalpel-0.3.0.1 couldn't compile with ghc-8.0.1.
The error message was something like:
```
src/Text/HTML/Scalpel/Internal/Select.hs:78:28: error:
• Couldn't match type ‘forall a. Maybe a’ with ‘CloseOffset’
Expected type: (TagSoup.Tag str, Int)
-> ((TagSoup.Tag str, CloseOffset), Int)
Actual type: (TagSoup.Tag str, Int)
-> ((TagSoup.Tag str, forall a. Maybe a), Int)
• In the first argument of ‘map’, namely ‘(first (, Nothing))’
In the expression: map (first (, Nothing))
In the expression:
map (first (, Nothing)) $ concat $ Map.elems state
```
When I remove `ImpredicativeTypes` extension, it compiles fine. Maybe it's because of the [Impredicative types brokenness](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#Impredicativetypesbrokenness).
I've never used this extension. Is it really …
=> failed to build with ghc-8.0.1

CHANGELOG.md, README.md, examples/complex-predicates/Main.hs, examples/generalized-repetition/Main.hs, examples/scalpel-examples.cabal, src/Text/HTML/Scalpel/Internal/Scrape.hs, tests/TestMain.hs
This commit adds the resolutions to #23 and #25 to README.md under a
new tips & tricks section. Full source code for each is given in a new
example as well.
Additionally a backtracking bug was found in `chroot` while
documenting these tricks and is fixed in this commit as well.
=> (#23, #25, #34) Document chroot tricks

CHANGELOG.md, benchmarks/Main.hs, scalpel.cabal, src/Text/HTML/Scalpel/Internal/Scrape.hs, src/Text/HTML/Scalpel/Internal/Scrape/StringLike.hs, src/Text/HTML/Scalpel/Internal/Select.hs, src/Text/HTML/Scalpel/Internal/Select/Types.hs, tests/TestMain.hs
This commit fixes two bugs that occur when using the `//` operator:
1) The first is that using any of the pluralized scrapers with a
selector created from one or more `//` operators will potentially
return duplicate tags. This occurs if there are multiple ways in
which a given tag may satisfy the selector.
2) The `//` operator does not force a decent from the current
context. For example, if one attempts to match a nested div
`<div id=a><div id=b></div></div>` with the selector
`"div" // "div"` the outer div will be matched.
In order to fix this bug without regressing on performance the entire
selection engine had to be re-written. The engine now features linear
time matching for tags as opposed to the probably exponential prior
implementation.
=> (#28) Fixes bug with nested selectors

README.md, benchmarks/Main.hs, examples/complex-predicates/Main.hs, examples/example-from-documentation/Main.hs, examples/generalized-repetition/Main.hs, examples/list-all-images/Main.hs, src/Text/HTML/Scalpel.hs, src/Text/HTML/Scalpel/Internal/Scrape.hs, src/Text/HTML/Scalpel/Internal/Select.hs, src/Text/HTML/Scalpel/Internal/Select/Combinators.hs, src/Text/HTML/Scalpel/Internal/Select/Types.hs, tests/TestMain.hs
This addresses Issue #29.
I've removed the classes `Selectable`, `TagName`, and `AttributeName` and replaced the last two with suitable data types.
I took @debug-ito's suggestions when altering `Selector` and `Selectable`. Does everyone approve of how I've chosen to change `TagName` and `AttributeName`?
=> Improve scalpel usage with OverloadedStrings enabled

CHANGELOG.md, src/Text/HTML/Scalpel/Internal/Scrape.hs, tests/TestMain.hs
This makes the pluralized scrapers return an empty list instead of
failing if there are no matching elements.
=> (#44) Make `withAll` always succeed

CHANGELOG.md, scalpel.cabal, src/Text/HTML/Scalpel/Internal/Scrape.hs, stack.yaml, tests/TestMain.hs
Scraper is made an instance of MonadFail using the transitional fail
package (https://hackage.haskell.org/package/fail). This allows
pattern matching in `<-` expressions to be evaluated to `mzero` when
the match fails instead of throwing an error.
=> (#43) Implement fail as mzero

CHANGELOG.md, src/Text/HTML/Scalpel.hs, src/Text/HTML/Scalpel/Internal/Scrape.hs, src/Text/HTML/Scalpel/Internal/Select.hs, tests/TestMain.hs
The position scraper returns the index of the current sub-tree within
the context of a `chroots` do-block.
=> (#38) Add position scraper

src/Text/HTML/Scalpel.hs, src/Text/HTML/Scalpel/Internal/Select.hs, src/Text/HTML/Scalpel/Internal/Select/Combinators.hs, src/Text/HTML/Scalpel/Internal/Select/Types.hs, tests/TestMain.hs
In order to implement this, AttributePredicate was changed from taking a single
attribute, with checkPreds responsible for applying it to each attribute, to now
taking a list of attributes.
Addresses #51
=> Add notP AttributePredicate combinator

CHANGELOG.md, scalpel-core/src/Text/HTML/Scalpel/Internal/Scrape.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Scrape/StringLike.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select.hs, scalpel/src/Text/HTML/Scalpel/Internal/Scrape/URL.hs
This was a holdover from when when the underlying data type was used as
keys in map. Now Text is used everywhere internally and this is no
longer required.
Issue #61
=>  Remove `Ord` constraint from public APIs

CHANGELOG.md, scalpel-core/src/Text/HTML/Scalpel/Core.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select/Combinators.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select/Types.hs, scalpel-core/tests/TestMain.hs, scalpel/src/Text/HTML/Scalpel.hs
`atDepth` allows for specifying the depth that a Selector must be at in
relation to the previous Selector or root node. For example the below
will select anchor tags that are direct children of a div tag.
```haskell
"div" // "a" `atDepth` 1
```
Issue #21
=> Add `atDepth` operator and misc fixes and optimizations

CHANGELOG.md, scalpel-core/src/Text/HTML/Scalpel/Core.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select/Types.hs, scalpel-core/tests/TestMain.hs, scalpel/src/Text/HTML/Scalpel.hs
A new selector, textSelector, is added that matches raw text nodes.
This can currently be used to capture floating text that is not directly
nested within other tags.
This is probably not super useful without the contextual awareness that
will be provided by #48.
Issue #70
=> Allow selecting bare text

.travis.yml, .travis/stack-lts-2.yaml, .travis/stack-lts-6.yaml, examples/html-to-markdown/Main.hs, examples/scalpel-examples.cabal, scalpel-core/scalpel-core.cabal, scalpel-core/src/Text/HTML/Scalpel/Core.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Scrape.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Select.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Serial.hs, scalpel-core/tests/TestMain.hs, scalpel/src/Text/HTML/Scalpel.hs
The approach utilizes a zipper like API to focus on sibling nodes and
execute scrapers on the focused nodes. Regression tests have been added
that shows that this solves the requirements in issues #41, and #45.
Issue #48
=> Initial support for scraping multiple sub-trees

.travis/stack-lts-2.yaml, .travis/stack-lts-6.yaml, CHANGELOG.md, README.md, examples/custom-user-agent/Main.hs, examples/scalpel-examples.cabal, scalpel/scalpel.cabal, scalpel/src/Text/HTML/Scalpel.hs, scalpel/src/Text/HTML/Scalpel/Internal/Scrape/URL.hs
This replaces 'curl' with 'http-client'/'http-client-tls' and updates
the related 'scrapeURL*' APIs accordingly.
In addition to the obvious API changes there is the additional behavior
change where scrapeURL now throws an exception if there is a networking
error instead of returning Nothing. This makes HTML scraping errors
distinguishable from networking issues.
Issue #58
=> Remove dependency on curl

scalpel-core/tests/TestMain.hs
It has gotten to the point where a failing test is very hard to find
out of the list of all ~80 tests just based on the HTML.
=> Add explicit labels for all tests

.travis.yml, .travis/stack-lts-20190117.yaml, .travis/stack-lts-3.yaml, .travis/stack-nightly-20190117.yaml, scalpel-core/src/Text/HTML/Scalpel/Internal/Scrape.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Serial.hs
Scalpel is currently disabled from stackage, with this change scalpel
will build with the latest stackage nightly.
Issue #85
=> Support GHC 8.8

scalpel/src/Text/HTML/Scalpel/Internal/Scrape/URL.hs
e.g. Wikipedia gives `UTF-8`, not `utf-8`
=> Match Content-Type case-insensitively

scalpel-core/src/Text/HTML/Scalpel/Internal/Scrape.hs, scalpel-core/src/Text/HTML/Scalpel/Internal/Serial.hs
I've tested that it builds and that the test suite passes
=> Adapt to removal of re-exports in mtl-2.3

.github/workflows/stack.yml
Move the stackage version earlier in the cache key and progressively try more general caches in the event of a miss.
=> Better optimized caching in GitHub CI

scalpel/src/Text/HTML/Scalpel.hs
`/` is used for italics in Haddock.
Currently the docs are rendered this way:
I didn't try building the docs after introducing the fix. However, I tried it in the [Haddock Dingus ](https://haddock-dingus.fly.dev/inputs/2374d82631404947) and it looks ok.
=> Fix markup: escape /'s
